### ISSUE TITLE
Principles vs Policy

### ISSUE THREAD

**Issue by rajido** [SoftDev4LS/open-source-software#18]
Today I have talked to people with experience writing policies for distributed organisations. They suggested we do release this document as “Open Source Software Principles” and not as a Policy. The idea would be organisations inline with this principles start to adopt the principles and end up turning this document into their policy. For instance in ELIXIR we could spread these principles and start to adopt them as a policy within some of their projects and later try to adopt the policy across all our distributed organisations.

**Comment by danielvaughan** [comment]
Yes principles does sound much better for the intended purpose.

**Comment by danielskatz** [comment]
Principles is what was done with data citation in FORCE11, and we are doing this again with software citation (https://www.force11.org/software-citation-principles)  The idea is that after the principles are generally accepted, we get stakeholders to endorse them, and then start activities to encourage and work with stakeholders to implement the principles.

**Comment by jhagberg** [comment]
I agree with the word Principles!

**Comment by rajido** [comment]
Thanks for the feedback. When this group was proposed ELIXIR technical coordinators also suggested to avoid the word policy. So with all this feedback I will rename the document to principles.
