### ISSUE TITLE
Collect and display level of engagement with the recommendations from individuals and organisations

### ISSUE THREAD

**Issue by rajido** [SoftDev4LS/open-source-software#22]
Several examples of how this is done in other initiatives:

- https://open-stand.org/about-us/principles/
- https://www.force11.org/group/joint-declaration-data-citation-principles-final
- https://cos.io/top/

Thanks to Michelle Barker for proposing this idea.

**Comment by rajido** [comment]
We can use our gitHub repo and gitHub pages to display the recommendations and levels of endorsement from organisations and individuals. We could collect this info via a google web form in a google spreadsheet and later display it with a javascript widget consuming the spreadsheet info. This way we can keep it simple not worrying for a web hosting space.

**Comment by rajido** [comment]
I have created a project to bring forward this idea. https://github.com/SoftDev4LS/open-source-software/projects/1

**Comment by ficolo** [comment]
I've found this 3 simple themes: 

[Immaculate](https://cdn.ampproject.org/c/siawyoung.com/immaculate/)
[Hyde](http://hyde.getpoole.com/)
[Beautiful Jekyll](http://deanattali.com/beautiful-jekyll/)

What do you think about it?

**Comment by rajido** [comment]
I like Beautiful Jekyll. My second choice would be Hyde

**Comment by rajido** [comment]
Available now at ... https://softdev4research.github.io/recommendations
